[project]
name = "selenium-browser-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.11.0",
    "nodriver>=0.47.0",
    "pyperclip>=1.9.0",
    "python-jose>=3.5.0",
]
